server:
  port: ${PORT:8080}

spring:
  application:
    name: ${APPLICATION_NAME:future_saas}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:future_saas}?options=-c%20TimeZone=Asia/Ho_Chi_Minh}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USER:postgres}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:123456}}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  sql:
    init:
      mode: always

  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.3-70b-versatile
          temperature: 0.7
      embedding:
        enabled: false

    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      embedding:
        enabled: true
        options:
          model: nomic-embed-text

    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 768
        table-name: vector_store

jwt:
  secret: ${JWT_SECRET:9a4f2c8d3b7a1e5f2g8h4j9k0l1m2n3o4p5q6r7s8t9u0v1w2x3y4z5a6b7c8d9e}
  access-expiration: ${JWT_ACCESS_EXPIRATION:3600000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

momo:
  partner-code: ${MOMO_PARTNER_CODE:MOMO}
  access-key: ${MOMO_ACCESS_KEY:F8BBA842ECF85}
  secret-key: ${MOMO_SECRET_KEY:K951B6PE1waDMi640xX08PD3vg6EkVlz}
  api-url: ${MOMO_API_URL:https://test-payment.momo.vn/v2/gateway/api/create}
  redirect-url: ${MOMO_REDIRECT_URL:http://localhost:3000/api/momo/callback}
  ipn-url: ${MOMO_IPN_URL:http://localhost:8080/api/momo/ipn}
  frontend-url: ${FRONTEND_URL:http://localhost:3000}

cloudinary:
  cloud-name: ${CLOUD_NAME:dmen8hyem}
  api-key: ${CLOUD_API_KEY:622878251667519}
  api-secret: ${CLOUD_API_SECRET:_o0mYsM0cWRNbO3VHu8NYk6yjbw}

vnpay:
  api-url: ${VNPAY_API_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
  tmn-code: ${VNPAY_TMN_CODE:D08O3Z1K}
  hash-secret: ${VNPAY_HASH_SECRET:9OQ1FB8DYHDQRP4PZEV7ZDCBRKDVLFAG}
  return-url: ${VNPAY_RETURN_URL:http://localhost:8080/api/subscriptions/vnpay-return}
  version: "2.1.0"
  command: "pay"
  order-type: "other"