server:
  port: ${PORT}

spring:
  application:
    name: ${APPLICATION_NAME}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:future_saas}?options=-c%20TimeZone=Asia/Ho_Chi_Minh
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  sql:
    init:
      mode: always

  ai:
    openai:
      base-url: ${CHAT_URL}
      api-key: ${CHAT_KEY_1}
      extend-key:
        key-2: ${CHAT_KEY_2}
        key-3: ${CHAT_KEY_3}
        key-4: ${CHAT_KEY_4}
      embedding:
        base-url: ${EMBEDDING_URL}
        api-key: ${EMBEDDING_KEY}
        options:
          model: ${EMBEDDING_MODEL}
      chat:
        options:
          model: ${CHAT_MODEL}
          temperature: 0.7
    retry:
      max-attempts: 10
      backoff:
        initial-interval: 2s
        max-interval: 120s
        multiplier: 5
      on-client-errors: false
      exclude-on-http-codes:
        - 400
        - 401
        - 403
        - 404
      on-http-codes:

    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        table-name: vector_store

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

momo:
  partner-code: ${MOMO_PARTNER_CODE}
  access-key: ${MOMO_ACCESS_KEY}
  secret-key: ${MOMO_SECRET_KEY}
  api-url: ${MOMO_API_URL}
  redirect-url: ${MOMO_REDIRECT_URL}
  ipn-url: ${MOMO_IPN_URL}
  frontend-url: ${FRONTEND_URL}

cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${CLOUD_API_KEY}
  api-secret: ${CLOUD_API_SECRET}

vnpay:
  api-url: ${VNPAY_API_URL}
  tmn-code: ${VNPAY_TMN_CODE}
  hash-secret: ${VNPAY_HASH_SECRET}
  return-url: ${VNPAY_RETURN_URL}
  version: "2.1.0"
  command: "pay"
  order-type: "other"

goong:
  api-key: ${GOONG_API_KEY}
  base-url: https://rsapi.goong.io
google:
  maps:
    api-key: ${GOOGLE_MAP_API_KEY}
payos:
  client-id: ${PAYOS_CLIENT_ID}
  api-key: ${PAYOS_API_KEY}
  checksum-key: ${PAYOS_CHECKSUM_KEY}
  return-url: ${PAYOS_RETURN_URL}
  cancel-url: ${PAYOS_CANCEL_URL}
